version: "3"

tasks:
  services:
    desc: Build all services to binaries
    cmds:
      - task: authService
      - task: projectService
      - task: websocketService

  authService:
    desc: Build the Go Authentication service
    dir: src/services/golang-auth-service
    cmds:
      - go build -o auth-service main.go

  projectService:
    desc: Build the Go Project service
    dir: src/services/golang-project-service
    cmds:
      - go build -o project-service

  websocketService:
    desc: Build the Go Websocket service
    dir: src/services/golang-websocket-service
    cmds:
      - go build -o websocket-service