version: '3'

env:
  CGO_LDFLAGS: "-lm"

tasks:
  runAllServices:
    desc: Run all Go services
    dir: src/services/service-runner
    interactive: true
    cmds:
      - go run main.go

  runAuthService:
    desc: Run the Go authentication service in its own terminal
    dir: src/services/golang-auth-service
    interactive: true
    cmds:
      - go run main.go

  runProjectService:
    desc: Run the Go project service in its own terminal
    dir: src/services/golang-project-service
    interactive: true
    cmds:
      - go run main.go

  runWebsocketService:
    desc: Run the Go websocket service in its own terminal
    dir: src/services/golang-websocket-service
    interactive: true
    cmds:
      - go run main.go

  runWebpage:
    desc: Run the Vite Webpage
    dir: src/Canary
    interactive: true
    cmds:
     - npm run dev

  lintPkgService:
    desc: Lint the Go package service with golangci-lint
    dir: src/pkg
    cmds:
      - golangci-lint run

  lintAuthService:
    desc: Lint the Go authentication service with golangci-lint
    dir: src/services/golang-auth-service
    cmds:
      - golangci-lint run

  lintProjectService:
    desc: Lint the Go project service with golangci-lint
    dir: src/services/golang-project-service
    cmds:
      - golangci-lint run

  lintWebsocketService:
    desc: Lint the Go websocket service with golangci-lint
    dir: src/services/golang-websocket-service
    cmds:
      - golangci-lint run

  lintServiceRunner:
    desc: Lint the Go service-runner with golangci-lint
    dir: src/services/service-runner
    cmds:
      - golangci-lint run

  lintAll:
    desc: Lint all Go services with golangci-lint
    cmds:
      - task: lintPkgService
      - task: lintAuthService
      - task: lintProjectService
      - task: lintWebsocketService
      - task: lintServiceRunner
    
  tidyPkgService:
    desc: Tidy the Go package service
    dir: src/pkg
    cmds:
      - go mod tidy
  
  tidyAuthService:
    desc: Tidy the Go authentication service
    dir: src/services/golang-auth-service
    cmds:
      - go mod tidy
  
  tidyProjectService:
    desc: Tidy the Go project service
    dir: src/services/golang-project-service
    cmds:
      - go mod tidy
  
  tidyWebsocketService:
    desc: Tidy the Go websocket service
    dir: src/services/golang-websocket-service
    cmds:
      - go mod tidy
  
  tidyServiceRunner:
    desc: Tidy the Go service-runner
    dir: src/services/service-runner
    cmds:
      - go mod tidy
  
  tidyAll:
    desc: Tidy all Go services
    cmds:
      - task: tidyPkgService
      - task: tidyAuthService
      - task: tidyProjectService
      - task: tidyWebsocketService
      - task: tidyServiceRunner
