version: '3'

env:
  CGO_LDFLAGS: "-lm"

tasks:
  runAllServices:
    desc: Run all Go services
    dir: src/services/service-runner
    interactive: true
    cmds:
      - go run main.go

  runAuthService:
    desc: Run the Go authentication service in its own terminal
    dir: src/services/golang-auth-service
    interactive: true
    cmds:
      - go run main.go

  runProjectService:
    desc: Run the Go project service in its own terminal
    dir: src/services/golang-project-service
    interactive: true
    cmds:
      - go run main.go

  runWebsocketService:
    desc: Run the Go websocket service in its own terminal
    dir: src/services/golang-websocket-service
    interactive: true
    cmds:
      - go run main.go

  runWebpage:
    desc: Run the Vite Webpage
    dir: src/Canary
    interactive: true
    cmds:
     - npm run dev

  lintPkgService:
    desc: Lint the Go package service with golangci-lint
    dir: src/pkg
    cmds:
      - golangci-lint run --timeout=5m

  lintAuthService:
    desc: Lint the Go authentication service with golangci-lint
    dir: src/services/golang-auth-service
    cmds:
      - golangci-lint run --timeout=5m

  lintProjectService:
    desc: Lint the Go project service with golangci-lint
    dir: src/services/golang-project-service
    cmds:
      - golangci-lint run --timeout=5m

  lintWebsocketService:
    desc: Lint the Go websocket service with golangci-lint
    dir: src/services/golang-websocket-service
    cmds:
      - golangci-lint run --timeout=5m

  lintServiceRunner:
    desc: Lint the Go service-runner with golangci-lint
    dir: src/services/service-runner
    cmds:
      - golangci-lint run --timeout=5m

  lintAll:
    desc: Lint all Go services with golangci-lint
    cmds:
      - task: lintPkgService
      - task: lintAuthService
      - task: lintProjectService
      - task: lintWebsocketService
      - task: lintServiceRunner

  fmtPkgService:
    desc: Format Go files in the pkg service
    dir: src/pkg
    cmds:
      - gofmt -w .

  fmtAuthService:
    desc: Format Go files in the authentication service
    dir: src/services/golang-auth-service
    cmds:
      - gofmt -w .

  fmtProjectService:
    desc: Format Go files in the project service
    dir: src/services/golang-project-service
    cmds:
      - gofmt -w .

  fmtWebsocketService:
    desc: Format Go files in the websocket service
    dir: src/services/golang-websocket-service
    cmds:
      - gofmt -w .

  fmtServiceRunner:
    desc: Format Go files in the service runner
    dir: src/services/service-runner
    cmds:
      - gofmt -w .

  fmtAll:
    desc: Format Go files across all Go services
    cmds:
      - task: fmtPkgService
      - task: fmtAuthService
      - task: fmtProjectService
      - task: fmtWebsocketService
      - task: fmtServiceRunner
    
  tidyPkgService:
    desc: Tidy the Go package service
    dir: src/pkg
    cmds:
      - go mod tidy
  
  tidyAuthService:
    desc: Tidy the Go authentication service
    dir: src/services/golang-auth-service
    cmds:
      - go mod tidy
  
  tidyProjectService:
    desc: Tidy the Go project service
    dir: src/services/golang-project-service
    cmds:
      - go mod tidy
  
  tidyWebsocketService:
    desc: Tidy the Go websocket service
    dir: src/services/golang-websocket-service
    cmds:
      - go mod tidy
  
  tidyServiceRunner:
    desc: Tidy the Go service-runner
    dir: src/services/service-runner
    cmds:
      - go mod tidy
  
  tidyAll:
    desc: Tidy all Go services
    cmds:
      - task: tidyPkgService
      - task: tidyAuthService
      - task: tidyProjectService
      - task: tidyWebsocketService
      - task: tidyServiceRunner
