version: '3'

tasks:
  runServices:
    desc: Run all backend services
    cmds:
      - task: runAuthService

  runAuthService:
    desc: Run the Go authentication service in its own terminal
    dir: src/Services/golang-auth-service
    interactive: true
    cmds:
      - go run main.go

  runProjectService:
    desc: Run the Go project service in its own terminal
    dir: src/Services/golang-project-service
    interactive: true
    cmds:
      - go run main.go

  runWebpage:
    desc: Run the Vite Webpage
    dir: src/Canary
    interactive: true
    cmds:
     - npm run dev